image:
  repository: ich777/steamcmd
  pullPolicy: IfNotPresent
  tag: eco@sha256:7b58e4cff85e87dda0e3638b2d449aef088c25db7ae6f672bfd85f9da02e7f2a

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: tcp
        port: 3001
  game:
    ports:
      game:
        protocol: udp
        port: 3000
  rcon:
    ports:
      rcon:
        protocol: tcp
        port: 3002

eco:
  game:
    id: 739590
    user: ""
    pass: ""
    validate: false

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
          env:
            STEAMCMD_DIR: "{{ .Values.persistence.steamcmd.mountPath }}"
            SERVER_DIR: "{{ .Values.persistence.serverfiles.mountPath }}"
            GAME_ID: "{{ .Values.cs2.game.id }}"
            USERNAME: "{{ .Values.cs2.game.user }}"
            PASSWRD: "{{ .Values.cs2.game.password }}"
            GAME_PARAMS: '{{ join " " .Values.cs2.game.params }}'
            VALIDATE: "{{ .Values.cs2.game.validate }}"

persistence:
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles

portal:
  open:
    enabled: false
